---
- name: copying files from jenkins
  copy:
    src: ../files/
    dest: /tmp/jenkins/

- name: creating jenkins namespace
  command: kubectl create namespace jenkins

- name: deploy jenkins
  command: kubectl create -f /tmp/jenkins/jenkins-deployment.yaml --namespace jenkins

- name: create the Service
  command: kubectl create -f /tmp/grafana/jenkins-service.yaml --namespace jenkins