---
- name: Ceeate user
  user:
    name: kubeadmin
    home: /home/kubeadmin

- name: Create Directory /home/kubeadmin/.kube
  file:
    path: /home/kubeadmin/.kube
    state: directory 

- name: Copy /etc/kubernetes/admin.conf to /home/kubeadmin/.kube/config
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/kubeadmin/.kube/config
    owner: kubeadmin
    
#- name: Aplicamos los permisos correspondientes
#  command: chown kubeadmin. /home/kubeadmin/.kube/config

- name: Config /etc/sudoers.d/kubeadmin
  lineinfile:
      path: /etc/sudoers.d/kubeadmin
      line: '{{item}}'
      state: present
      create: yes
  with_items:
     - 'ALL            ALL = (ALL) NOPASSWD: ALL'


- name: Allow kubernetes to properly handle traffic with the firewall
  lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: "{{item}}"
      state: present
      backup: yes
      create: yes
  with_items:
     - 'net.bridge.bridge-nf-call-ip6tables = 1'
     - 'net.bridge.bridge-nf-call-iptables = 1'