---
- name: Set timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid

- name: Install
  dnf:
    name: '{{ item }}'
    state: 'latest'
  loop:
    - nfs-utils
    - rpcbind
    - chrony
    - python3
    - nfs4-acl-tools
    - wget

#- name: Active Chrony
#  service:
#    name: chronyd
#    state: started

#- name: Active Chrony
#  service:
#    name: chronyd
#    enabled: true

- name: enable chronyd
  become: yes
  command: /usr/bin/systemctl enable chronyd

- name: start chronyd 
  become: yes
  command: /usr/bin/systemctl start chronyd 


- name: Active ntp
  shell: timedatectl set-ntp true

- name: "Disable SELINUX"
  selinux:
    state: disabled
