---
- name: updating SO
  dnf:
    name: "*"
    state: latest

- name: Unconditionally reboot the machine with all defaults
  reboot:

- name: Set timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid

- name: Install
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - nfs-utils
    - rpcbind
    - chrony
    - python3
    - nfs4-acl-tools
    - wget

- name: Active Chrony
  service:
    name: chronyd
    enabled: true
    state: started

- name: Active ntp
  command: timedatectl set-ntp true

- name: "Disable SELINUX"
  selinux:
    state: disabled
