---
- name: "Create /srv/nfs directory"
  file:
    path: /srv/nfs
    state: directory
    owner: adminUsername
    group: adminUsername
    mode: '0775'

- name: Install packages
  dnf:
    name: 
      - nfs-utils
      - net-tools
    state: 'latest'
    
#- name: Enable and run nfs-server 
#  systemctl:
#    name: nfs-server
#    enabled: yes
#    state: started

- name: enable chronyd
  become: yes
  command: systemctl  enable nfs-server

- name: start chronyd 
  become: yes
  command: systemctl start nfs-server

- name: Copy exports file
  template:
    src: etcExports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: "Read again /etc/exports 1"
  command:
    cmd: exportfs -r

- name: "Read again /etc/exports 2"
  command:
    cmd: exportfs -s

#- name: Enable and run firewall
#  systemd:
#    state: restarted
#    daemon_reload: yes
#    name: firewalld
#    enabled: yes

- name: run firewall 
  become: yes
  command: systemctl enable firewalld

- name: start firewall 
  become: yes
  command: systemctl start firewalld

- name: Open ports
  firewalld:
    service: "{{item}}"
    permanent: true
    state: enabled
  with_items:
    - nfs
    - rpc-bind
    - mountd

#- name: Reload firewall config 
#  systemd:
#    name: firewalld
#    state: reloaded

- name: reolad firewall 
  become: yes
  command: firewall-cmd --reload