---
- name: Create /srv/nfs directory
  file:
    path: /srv/nfs
    state: directory
    owner: adminUsername
    group: adminUsername
    mode: '0775'

- name: Install packages
  dnf:
    name: 
      - nfs-utils
      - net-tools
    state: 'latest'
    
#- name: Enable and run nfs-server 
#  systemctl:
#    name: nfs-server
#    enabled: yes
#    state: started

- name: enable chronyd
  command: systemctl  enable nfs-server

- name: start chronyd 
  command: systemctl start nfs-server

- name: Update modification and access time of given file
  copy:
    dest: /etc/exports
    content: |
      /srv/nfs {{ (hostvars[inventory_hostname]['publicIp'][0].ip) }}(sync,wdelay,hide,no_subtree_check,sec=sys,rw,secure,root_squash,no_all_squash)
      /srv/nfs {{ (hostvars[inventory_hostname]['publicIp'][1].ip) }}(sync,wdelay,hide,no_subtree_check,sec=sys,rw,secure,root_squash,no_all_squash)
      /srv/nfs {{ (hostvars[inventory_hostname]['publicIp'][2].ip) }}(sync,wdelay,hide,no_subtree_check,sec=sys,rw,secure,root_squash,no_all_squash)

- name: "Read again /etc/exports 1"
  command:
    cmd: exportfs -r

- name: "Read again /etc/exports 2"
  command:
    cmd: exportfs -s

#- name: Enable and run firewall
#  systemd:
#    state: restarted
#    daemon_reload: yes
#    name: firewalld
#    enabled: yes

- name: run firewall 
  command: systemctl enable firewalld

- name: start firewall 
  command: systemctl start firewalld

- name: Open ports
  firewalld:
    service: "{{item}}"
    permanent: true
    state: enabled
  with_items:
    - nfs
    - rpc-bind
    - mountd

#- name: Reload firewall config 
#  systemd:
#    name: firewalld
#    state: reloaded

- name: reolad firewall 
  command: firewall-cmd --reload