all:
  vars:
     ansible_python_interpreter: '/usr/bin/python3'
     publicIp:
        - {"name": vm-master-nfs, "ip":104.45.24.68, "hostname":vm-master-nfs}
        - {"name": vm-worker1, "ip":104.45.21.214, "hostname":vm-worker1}
        - {"name": vm-worker2, "ip":104.45.21.154, "hostname":vm-worker2}
  children:
    MasterNfs:
      hosts:
        vm-master-nfs:
          ansible_host: '{{publicIp[0].ip}}'
          ansible_user: adminUsername
    Workers:
      hosts:
        vm-worker1:
          ansible_host: '{{publicIp[1].ip}}'
          ansible_user: adminUsername
        vm-worker2:
          ansible_host: '{{publicIp[2].ip}}'
          ansible_user: adminUsername       
