all:
  vars:
     ansible_python_interpreter: '/usr/bin/python3'
     publicIp:
        - {"name": vm-master-nfs, "ip":13.69.120.144, "hostname":vm-master-nfs, "user":adminUsername}
        - {"name": vm-worker1, "ip":40.68.199.115, "hostname":vm-worker1, "user":adminUsername}
        - {"name": vm-worker2, "ip":40.68.199.118, "hostname":vm-worker2, "user":adminUsername}
  children:
    MasterNfs:
      hosts:
        vm-master-nfs:
          ansible_host: '{{publicIp[0].ip}}'
          ansible_user: '{{publicIp[0].user}}'
    Workers:
      hosts:
        vm-worker1:
          ansible_host: '{{publicIp[1].ip}}'
          ansible_user: '{{publicIp[1].user}}'
        vm-worker2:
          ansible_host: '{{publicIp[2].ip}}'
          ansible_user: '{{publicIp[1].user}}'       
