---
- name: Open ports
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
  with_items:
    - 10250/tcp
    - 30000/tcp
    - 32767/tcp
    - 8285/udp
    - 8472/udp

- name: reolad service firewall 
  command: firewall-cmd --reload

- name: Get file with command
  copy: 
    src: ./join_command
    dest: ./join_command  

- name: get command
  shell: cat ./join_command
  register: join_command_run

- name: Print command
  debug: msg="{{join_command_run.stdout}}"
  
- name: Run join
  shell: "{{join_command_run.stdout}}"